blank_issues_enabled: true
contact_links:
  - name: OpenNotes Discord Community
    url: https://go.opennotes.openlay.com/discord
    about: Reach out to us directly & discuss your issues, suggestions & other feedback!
